services:
  - type: web
    name: elexercise-api
    runtime: node
    plan: free
    rootDir: .
    buildCommand: npm install && npm run build --workspace=apps/api
    startCommand: npm run start --workspace=apps/api
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: ALLOWED_ORIGIN
        sync: false
